language: python

services:
  - redis-server

cache:
  directories:
  - data
  - $HOME/.cache/pip

install:
  - 'pip install -r requirements.txt'
  - 'pip install -r test-requirements.txt'

before_script:
  - './ext/fetch-data.sh'

script:
  - 'flake8 --ignore=F403 .'
  - 'python basil_refapi/migrate.py'
  - 'py.test tests'

env:
  global:
    - REDIS_HOST=localhost
    - BLUEPRINTS_FILE="data/blueprints.yaml"

matrix:
  include:
    - python: '2.7'

notifications:
  email: false

git:
  depth: 3

sudo: false